apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo-api
  labels:
    app: devops-demo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-demo-api
  template:
    metadata:
      labels:
        app: devops-demo-api
    spec:
      containers:
      - name: api
        image: devops-demo-api:latest
        imagePullPolicy: Never  
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
