apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
  labels:
    app: devops-demo-api
spec:
  selector:
    app: devops-demo-api
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  type: LoadBalancer